# Generated by Django 5.0.6 on 2024-06-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('commentaire', models.CharField(max_length=256)),
                ('date_publication', models.DateField(auto_now=True)),
            ],
        ),
    ]
